### ISSUE TITLE
MySQLError.basicPacket: Unrecognized basic packet. When using a Docker MySQL container

### ISSUE THREAD

**Issue by frivas** [vapor/mysql-kit#193]
Hello, 

The following error is thrown when using a MySQL docker container. 

**Versions used:**
- MySQL 8.0.11 (created using: docker pull mysql/mysql-server:latest)
- Vapor 3.0.5 
- Fluent 3.0.0-rc.4.0.2
- Fluent MySQL 3.0.0-rc.4.0.3
- SQL 2.0.0-beta.3

**Steps to reproduce:**

**1.-** ```$ docker run --name mysql -e MYSQL_USER=<user> -e MYSQL_PASSWORD=<password> -e MYSQL_DATABASE=<db> -p 3306:3306 -d mysql/mysql-server:latest```

**2.-** ```$ docker mysql logs```
Get the GENERATED PASSWORD

**3.-** ```$ docker exec -it mysql mysql -uroot -p```

**4.-** ```mysql> ALTER USER 'root'@'localhost' IDENTIFIED BY '<password>';```

**5.-** ```mysql> create user '<user>'@'localhost' identified by '<password>';```

**6.-** ```mysql> grant all privileges on *.* to '<user>'@'localhost';```

**7.-** ```mysql> alter user '<user>'@'localhost' identified with mysql_native_password by '<password>';```

**8.- Configure the DB in this way:**
```swift
	try services.register(FluentMySQLProvider())
	var databases = DatabasesConfig()
	let databaseConfig = MySQLDatabaseConfig(hostname: "127.0.0.1", port: 3306, username: "<user>", password: "<password>", database: "<db>")
	let mysqlDB = MySQLDatabase(config: databaseConfig)

	databases.add(database: mysqlDB, as: .mysql)
	databases.enableLogging(on: .mysql)
	services.register(databases)
```

**9.- Create a Model like such:**
```swift
import Foundation
import FluentMySQL
import Vapor
import Fluent

struct Post: Content, MySQLModel, Migration {
	var id: Int?
	var title: String
	var strap: String
	var content: String
	var category: Int
	var slug: String
	var date: Date
	
	static func prepare(on connection: MySQLConnection) -> Future<Void> {
		return MySQLDatabase.create(self, on: connection) { builder in
			builder.field(for: \.id, type: .bigint(), .notNull)
			builder.field(for: \.title)
			builder.field(for: \.strap)
			builder.field(for: \.category)
			builder.field(for: \.slug)
			builder.field(for: \.date)
			builder.field(for: \.content, type: .text(), .notNull)
		}
	}
}
```

**When running the project the error shown is something like:**
[ INFO ] Migrating 'mysql' database (MigrationConfig.swift:69)
⚠️ [MySQLError.basicPacket: Unrecognized basic packet.] [<path_to_project>/.build/checkouts/mysql.git-1890032512239690518/Sources/MySQL/Pipeline/MySQLPacketDecoder.swift:117:29]
Program ended with exit code: 1

A solution proposed by @tanner0101 is configuring the DB like such:
```swift
	let databaseConfig = MySQLDatabaseConfig(hostname: "127.0.0.1", port: 3306, username: "<user>", password: "<password>", database: "<db>", transport:  MySQLTransportConfig.unverifiedTLS)
```

However once the authentication method had been changed to ```mysql_native_password``` it does not work, it has to be ```caching_sha2_password```.

**Comment by cclion** [comment]
I also have this problem

**Comment by chinabrant** [comment]
me too

**Comment by tanner0101** [comment]
As @frivas mentioned, the workaround for 8.0.4+ is to use `caching_sha2_password` over TLS. If `mysql_native_password` is required, you can use < 8.0.4 where that is the default. I'll look into finding a solution for this.

**Comment by nick3389** [comment]
@tanner0101 I have the same issue when trying connecting to an azure database with .unverifiedTLS. Is there any progress with this issue? I use FlunetMySQLDriver for the mysql database.

**Comment by JinfeiChen** [comment]
how to solve this problem?

**Comment by tanner0101** [comment]
Moving here: https://github.com/vapor/mysql-nio/pull/20

Until that is merged, Vapor's MySQL only supports `caching_sha2_password` over TLS.
