### ISSUE TITLE
Random `Connection is closed.` errors 

### ISSUE THREAD

**Issue by jdmcd** [vapor/mysql-kit#199]
Every now and then, seemingly without pattern or especially heavy load, my production server will return a `Connection is closed.` response when trying to do database work. This happens regardless of the 1000 max connections configured per event loop and a total of 8000 connections available on the database. It occurs randomly and is hard to reproduce, but happens on multiple different routes. This also occasionally happens in unit tests. 

I'll work on trying to put together a reproduction case.

**Comment by mcdappdev** [comment]
Unfortunately it's returning 4 rows :( The route hits an external API for authentication and then once it receives an `OK` from that API it does:

```swift
return School.query(on: req).all()
```

**Comment by mcdappdev** [comment]
For what it's worth, I'm now seeing this error propagate across various endpoints. I actually had to restart my servers to get the endpoint to serve data. MySQL database connections are sitting happily at 4 on AWS RDS 🤔
