### ISSUE TITLE
Using no password with an account in MySQL causes this error

### ISSUE THREAD

**Issue by grubicv** [vapor/mysql-kit#204]
https://github.com/vapor/mysql/blob/8717e4a6389ff1ff56801f4e6411309105945c62/Sources/MySQL/Connection/MySQLConnectionHandler.swift#L131

nil should be allowed here, so that we can use MySQL users that have no password (for example root with no password)

**Comment by tanner0101** [comment]
Passing an empty string should work. Going forward, MySQLNIO 1.0.0 will allow `nil` here.
