### ISSUE TITLE
Errors related to Float80 when  trying to compile on Raspberry Pi 3 

### ISSUE THREAD

**Issue by ozitrance** [vapor/mysql-kit#215]
I am trying to compile a vapor project that uses this repository on a Raspberry Pi 3 (w/ Ubuntu 16.04) but it fails with the errors below.
I might be wrong but from what I was able to find, Float80 is not available for ARM-based platforms. 

Is there a way to overcome this error?

Thanks in advance!

The errors I get are: 
/home/xxx/yyy-master/.build/checkouts/mysql.git-1505813759/Sources/MySQL/Connection/MySQLData.swift:219:24: error: use of unresolved identifier 'Float80'
            .flatMap { Float80($0) }
                       ^~~~~~~
Swift.Float:1:15: note: did you mean 'Float'?
public struct Float {
              ^
Swift.Float32:1:18: note: did you mean 'Float32'?
public typealias Float32 = Float
                 ^
Swift.Float64:1:18: note: did you mean 'Float64'?
public typealias Float64 = Double
                 ^
SwiftGlibc.float_t:1:18: note: did you mean 'float_t'?
public typealias float_t = Float
                 ^
/home/xxx/yyy-master/.build/checkouts/mysql.git-1505813759/Sources/MySQL/Connection/MySQLData.swift:237:36: error: use of unresolved identifier 'Float80'
                        .flatMap { Float80($0) }
                                   ^~~~~~~
Swift.Float:1:15: note: did you mean 'Float'?
public struct Float {
              ^
Swift.Float32:1:18: note: did you mean 'Float32'?
public typealias Float32 = Float
                 ^
Swift.Float64:1:18: note: did you mean 'Float64'?
public typealias Float64 = Double
                 ^
SwiftGlibc.float_t:1:18: note: did you mean 'float_t'?
public typealias float_t = Float

**Comment by jmarkstar** [comment]
I got that error on my ODROID XU4 too but I only changed `Float` by `Float80` in that class and it worked.

**Comment by tanner0101** [comment]
Fixed in 3.2.6, thanks!
