### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by anatoliykant** [vapor/mysql-kit#242]
There is a need to add at least a TL;DR README from https://docs.vapor.codes/3.0/mysql/getting-started/ 
Thx

**Comment by tanner0101** [comment]
This package is built on `SQLKit` which is now documented in its README: https://github.com/vapor/sql-kit

This package's README should reference that one and include information specific to configuring a MySQL connection pool.

**Comment by tanner0101** [comment]
Added, thanks!
