### ISSUE TITLE
Custom JSONDecoder

### ISSUE THREAD

**Issue by florianreinhart** [vapor/mysql-kit#252]
It should be possible to specific a custom JSONDecoder (ideally per column) for decoding.

In my database there is a JSON column that contains `Date` values encoded as Unix timestamps.

**Comment by tanner0101** [comment]
Fixed here: https://github.com/vapor/mysql-kit/pull/285, thanks!

Side note, if you're using Fluent, you can use `@Timestamp`with `.unix` format to parse this without needing to configure a custom JSON coder: https://docs.vapor.codes/4.0/fluent/model/#timestamp-format

```swift
// Stores date as seconds since UNIX epoch
@Timestamp(key: "updated_at", on: .update, format: .unix)
var updatedAt: Date?
```
