### ISSUE TITLE
Value of type 'DatabaseQuery' has no member 'idKey'  - FluentMySQLDriver 4.0.0-beta.3

### ISSUE THREAD

**Issue by anmolrajpal** [vapor/mysql-kit#259]
![Screenshot 2020-02-22 at 3 36 04 PM](https://user-images.githubusercontent.com/53750739/75090479-513c2c80-5589-11ea-8f5e-ef282483836c.png)

> Value of type 'DatabaseQuery' has no member 'idKey'  - FluentMySQLDriver 4.0.0-beta.3

**Comment by tanner0101** [comment]
Running `swift package update` or Xcode > Swift Packages > Update to latest should fix this.
