### ISSUE TITLE
Build error on Swift CLI project

### ISSUE THREAD

**Issue by sebleclerc** [vapor/mysql-kit#272]
I'm creating a CLI tool using Swift and I need to query a MySql DB locally. I tried to add this packages as a dependency to my project but build fail.

I did add the latest `libressl` with brew, updated search path as directed from #6 but I still get this error:

```
Undefined symbols for architecture x86_64:
  "_TLS_method", referenced from:
      _CNIOOpenSSL_TLS_Method in CNIOOpenSSL.o
  "_X509_up_ref", referenced from:
      _CNIOOpenSSL_X509_up_ref in CNIOOpenSSL.o
     (maybe you meant: _CNIOOpenSSL_X509_up_ref)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is this package should work outside of Vapor? Thanks! :)

**Comment by 0xTim** [comment]
@sebleclerc you also need to install `pkg-config`

**Comment by sebleclerc** [comment]
@0xTim From the output of `brew list` I see pkg-config installed. And `pkg-config --version` is 0.29.2

**Comment by 0xTim** [comment]
@sebleclerc if you remove the linker settings does it now work? IIRC the linker settings will override all settings so that pkg-config won't pick it up

**Comment by sebleclerc** [comment]
@0xTim Ok I managed to have it compiling. Seems like generating the Xcode project from swift command line works better than create the project from Xcode.

Now... I need to find out how to query my database from a `MySQLDatabase` object
