### ISSUE TITLE
SimpleQuery fails decoding data version : +3.0.0 

### ISSUE THREAD

**Issue by pankajsoni19** [vapor/mysql-kit#279]
I am connecting to MySql server running on top of ClickHouse DB. 

```
var connection: MySQLConnection
let query = "SELECT count(*) AS count FROM ch_recognitions;"
connection.simpleQuery(query).

there are packets being received in `decodeTextProtocol` >
case .rows(let columnCount, var remaining):
```

however it the code just loops on needMoreData

**Comment by pankajsoni19** [comment]
MySQL packet boundary is multiple of 2.
I am getting a packet for column entry for 28 bytes but data ends at 27 bytes. there is a padding of empty 0 byte in the end which is causing issue, as trailing data is not cleared. This can cause serious issues at runtime.

**Comment by pankajsoni19** [comment]
wireshark 

```
char peer1_2[] = { /* Packet 295 */
0x01, 0x00, 0x00, 0x01, 0x01, 0x1c, 0x00, 0x00, 
0x02, 0x03, 0x64, 0x65, 0x66, 0x00, 0x00, 0x00, 
0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x00, 0x0c, 
0x3f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0xa0, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 
0x03, 0x07, 0x36, 0x34, 0x30, 0x38, 0x33, 0x35, 
0x31 };
```

**Comment by tanner0101** [comment]
Could you try using `query` instead of `simpleQuery` and see if the issue persists?

I'm unfortunately not able to repro this with the info here. More information would help. A `.pcap` file for replaying the session would probably do it if you already have wireshark setup. 

The best way to repro would be a small project that exhibits the bug that I can dig into.

**Comment by pankajsoni19** [comment]
This was for connecting with Clickhouse Server. It doesn't support parameterised queries. Thus the reason to use simpleQuery.
I have since switched to using Rest protocol since I couldn't fix the sql driver easily.
