### ISSUE TITLE
Not working with Swift Playground (4.4.1) on iPadOS 17.4.

### ISSUE THREAD

**Issue by pTech01** [vapor/mysql-kit#324]
### Describe the issue

Not working with Swift Playground (4.4.1) on iPadOS 17.4.

### Vapor version

don‘t know.

### Operating system and version

iPadOS 17.4

### Swift version

Swift Playground 4.4.1

### Steps to reproduce

adding this package using the swift playground menu.
Error Message: >target type „ClangTarget“ is not supported< 

### Outcome

Error Message: >target type „ClangTarget“ is not supported<

**Comment by 0xTim** [comment]
Closing in favour of https://github.com/vapor/mysql-nio/issues/107
